export type ColorMode = 'light' | 'dark';

export type ColorModePreference = ColorMode | 'system';

/** Flat token keys map directly to root CSS variables. */
export interface DesignTokens {
  'color-primary': string;
  'color-primary-hover': string;
  'color-primary-active': string;
  'color-background': string;
  'color-foreground': string;
  'color-surface': string;
  'color-surface-hover': string;
  'color-muted': string;
  'color-border': string;
  'color-border-subtle': string;
  'color-text-primary': string;
  'color-text-secondary': string;
  'color-text-muted': string;
  'color-text-inverse': string;
  'color-focus-ring': string;
  'color-success': string;
  'color-error': string;
  'color-warning': string;
  'color-info': string;
  'font-display': string;
  'font-sans': string;
  'font-mono': string;
  'text-xs': string;
  'text-sm': string;
  'text-base': string;
  'text-md': string;
  'text-lg': string;
  'text-xl': string;
  'text-2xl': string;
  'text-3xl': string;
  'text-4xl': string;
  'text-5xl': string;
  'leading-tight': string;
  'leading-normal': string;
  'leading-relaxed': string;
  'tracking-tighter': string;
  'tracking-tight': string;
  'tracking-normal': string;
  'tracking-wide': string;
  'tracking-wider': string;
  'shadow-sm': string;
  'shadow-md': string;
  'shadow-lg': string;
  'shadow-color': string;
  'radius-sm': string;
  'radius-md': string;
  'radius-lg': string;
  'radius-full': string;
  'space-1': string;
  'space-2': string;
  'space-3': string;
  'space-4': string;
  'space-5': string;
  'space-6': string;
  'space-7': string;
  'space-8': string;
  'duration-instant': string;
  'duration-fast': string;
  'duration-normal': string;
  'duration-slow': string;
  'ease-standard': string;
  'ease-in': string;
  'ease-out': string;
}
