export const E2E_TEST_IDS = {
  hostNameInput: 'host-name-input',
  hostCreateRoomButton: 'host-create-room-button',
  hostScrollRegion: 'host-scroll-region',
  hostActionZone: 'host-action-zone',
  joinRoomCodeInput: 'join-room-code-input',
  joinNameInput: 'join-name-input',
  joinRoomButton: 'join-room-button',
  joinErrorAlert: 'join-error-alert',
  hostErrorAlert: 'host-error-alert',
  lobbyStartGameButton: 'lobby-start-game-button',
  lobbyWaitingForHostButton: 'lobby-waiting-for-host-button',
  lobbyPresentationButton: 'lobby-presentation-button',
  lobbyPresentationStage: 'lobby-presentation-stage',
  lobbyScrollRegion: 'lobby-scroll-region',
  lobbyActionZone: 'lobby-action-zone',
  writingPhase: 'writing-phase',
  writingScrollRegion: 'writing-scroll-region',
  writingActionZone: 'writing-action-zone',
  writingCarriedLine: 'writing-carried-line',
  writingLineInput: 'writing-line-input',
  writingWordSlots: 'writing-word-slots',
  writingSubmitLineButton: 'writing-submit-line-button',
  waitingPhase: 'waiting-phase',
  revealPhase: 'reveal-phase',
  revealPoemButton: 'reveal-poem-button',
  revealPresentationButton: 'reveal-presentation-button',
  revealPresentationStage: 'reveal-presentation-stage',
  revealStageNextLineButton: 'reveal-stage-next-line-button',
  poemActions: 'poem-actions',
  poemDoneButton: 'poem-done-button',
  sessionComplete: 'session-complete',
  roomFavoriteCrown: 'room-favorite-crown',
  sessionRecapShareButton: 'session-recap-share-button',
  poemSaveImageButton: 'poem-save-image-button',
  recapExportButton: 'recap-export-button',
} as const;

export type E2ETestId = (typeof E2E_TEST_IDS)[keyof typeof E2E_TEST_IDS];
