import { describe, it, expect } from 'vitest';
import { verifyGuestToken } from '../../convex/lib/guestToken';
import { signGuestToken } from '../../lib/guestToken'; // Use the working signer to generate tokens

describe('Convex guestToken verification', () => {
  it('verifies a valid token generated by the client lib', async () => {
    const guestId = 'test-convex-guest-123';
    const token = await signGuestToken(guestId);

    const result = await verifyGuestToken(token);
    expect(result).toBe(guestId);
  });

  it('rejects tampered token payload', async () => {
    const guestId = 'test-convex-guest-tampered';
    const token = await signGuestToken(guestId);

    const [payload, signature] = token.split('.');
    const tamperedPayload = 'X' + payload.slice(1);
    const tamperedToken = `${tamperedPayload}.${signature}`;

    await expect(verifyGuestToken(tamperedToken)).rejects.toThrow(
      'Token signature verification failed'
    );
  });
});
