// Export the Pen Pals cast as static art data for the app.
// bun explorations/avatars/tools/export-art.js components/ui/avatarArt.ts
// Bodies, faces and props become plain path data; the app composes them with size-aware
// stroke widths, so no geometry is computed at runtime.
import penPals from '../src/casts/pen-pals.js';
import {
  faceParts,
  propParts,
  PROP_ANCHOR,
  PROP_ROT,
  DEFAULT_ANCHORS,
  MOODS,
  f,
} from '../src/engine.js';

const out = process.argv[2];
if (!out) throw new Error('usage: export-art.js <out.ts>');

const VARIANTS = ['small', 'regular', 'large'];
const kFor = (v, mood = 'idle') => ({
  v,
  small: v === 'small',
  large: v === 'large',
  mood,
  ink: 1,
  edge: 1,
});
const visible = (p, k) =>
  !(p.only && [].concat(p.only).every((o) => o !== k.v)) &&
  !(p.skip && [].concat(p.skip).includes(k.v));

/** Normalize an engine part into the app's part shape. */
function toPart(p) {
  if (!['shape', 'fill', 'line', 'dot'].includes(p.t))
    throw new Error(`unsupported part kind ${p.t}`);
  const part = { kind: p.t, d: p.d };
  if (p.fill != null && p.fill !== 'none') part.fill = p.fill;
  if (p.color) part.color = p.color;
  if (p.w != null && p.w !== 1) part.weight = Math.round(p.w * 1000) / 1000;
  if (p.tf) part.transform = p.tf;
  if (p.op != null) part.opacity = p.op;
  if (p.soft) part.soft = true;
  if (p.edge === false) part.noEdge = true;
  return part;
}

const art = {};
for (const ch of penPals.chars) {
  const table = [];
  const index = new Map();
  const variants = {};
  const faces = {};
  for (const v of VARIANTS) {
    const k = kFor(v);
    const drawn = ch.draw(k);
    if (drawn.over?.length)
      throw new Error(`${ch.id}: overlay parts are not exported`);
    variants[v] = drawn.parts
      .filter((p) => visible(p, k))
      .map((p) => {
        const part = toPart(p);
        const key = JSON.stringify(part);
        if (!index.has(key)) {
          index.set(key, table.length);
          table.push(part);
        }
        return index.get(key);
      });
    faces[v] = {};
    for (const mood of MOODS) {
      const face = faceParts(penPals.face, drawn.face, kFor(v, mood));
      faces[v][mood] = { transform: face.tf, parts: face.parts.map(toPart) };
    }
  }
  const anchors = {
    ...DEFAULT_ANCHORS,
    ...ch.draw(kFor('regular')).anchors,
  };
  const props = {};
  for (const [prop, anchorName] of Object.entries(PROP_ANCHOR)) {
    const [x, y, r = 0, sc = 1] = anchors[anchorName];
    if (sc !== 1)
      throw new Error(`${ch.id}: scaled prop anchors are not exported`);
    const turn = r + (prop === 'crown' || prop === 'moon' ? 0 : PROP_ROT[prop]);
    props[prop] =
      `translate(${f(x)} ${f(y)})${turn ? ` rotate(${f(turn)})` : ''}`;
  }
  art[ch.id] = { name: ch.name, parts: table, variants, faces, props };
}

// Props are drawn at 92% of the character's ink so they sit behind the character's outline.
const PROP_INK = 0.92;
const props = {};
for (const name of Object.keys(PROP_ANCHOR)) {
  props[name] = propParts(name, kFor('regular')).map((p) => {
    const part = toPart(p);
    part.weight = Math.round((p.w ?? 1) * PROP_INK * 1000) / 1000;
    return part;
  });
}

const header = `// Generated by explorations/avatars/tools/export-art.js from the Pen Pals cast in
// explorations/avatars/src/casts/pen-pals.js. Do not edit by hand: change the cast
// source, then rerun the exporter and Prettier. Coordinates are a 100 unit box;
// \`weight\` is a multiple of the size-aware ink width, \`fill: 'ink'\` follows the
// ink color, and \`soft\` parts (cheeks, tongues, eye shine, texture lines) are left
// out of outlined spectators.
`;
const body = `
import type { AvatarId } from '@/lib/avatars';

export type AvatarArtPart = {
  kind: 'shape' | 'fill' | 'line' | 'dot';
  d: string;
  fill?: string;
  color?: string;
  weight?: number;
  transform?: string;
  opacity?: number;
  soft?: true;
  noEdge?: true;
};

export type AvatarVariant = 'small' | 'regular' | 'large';
export type AvatarMood = ${MOODS.map((m) => `'${m}'`).join(' | ')};
export type AvatarProp = ${Object.keys(PROP_ANCHOR)
  .map((p) => `'${p}'`)
  .join(' | ')};

type AvatarFace = { transform: string; parts: readonly AvatarArtPart[] };

export type AvatarCharacterArt = {
  name: string;
  /** Unique parts; each variant lists the indexes it draws, in paint order. */
  parts: readonly AvatarArtPart[];
  variants: Record<AvatarVariant, readonly number[]>;
  faces: Record<AvatarVariant, Record<AvatarMood, AvatarFace>>;
  /** Where each prop sits on this character. */
  props: Record<AvatarProp, string>;
};

export const AVATAR_ART = ${JSON.stringify(art)} satisfies Record<AvatarId, AvatarCharacterArt>;

export const AVATAR_PROP_ART = ${JSON.stringify(props)} satisfies Record<AvatarProp, readonly AvatarArtPart[]>;
`;
await Bun.write(out, header + body);
console.log(`${out}: ${(header + body).length} bytes`);
